package/yast2-users.changes, package/yast2-users.spec, src/modules/UsersSimple.pm
manually tested and works. Empty root password is not problem as it is not allowed ( also tested ).
=> Fix zero pwd

package/yast2-users.changes, package/yast2-users.spec, src/modules/Users.pm
This solves [bsc#928607](https://bugzilla.suse.com/show_bug.cgi?id=928607). Manual tested and writing OpenQA tests right now.
=> Don't check encrypted user passwords

testsuite/tests/CheckUser.out, testsuite/tests/CheckUser.rb
Add basic test for Users.CheckUser function.
=> Add basic CheckUser tests

package/yast2-users.changes, package/yast2-users.spec, src/autoyast-rnc/users.rnc
Port of https://github.com/yast/yast-users/pull/73.
=> Fix AutoYaST schema for SLE 12 GA

package/yast2-users.changes, package/yast2-users.spec
Fixes version number for this package (my fault) as 3.1.36 exists already in SP1.
=> Fix version SLE12 GA

package/yast2-users.changes, package/yast2-users.spec, src/autoyast-rnc/users.rnc
Fixes [bsc#954412](https://bugzilla.suse.com/show_bug.cgi?id=954412) for this module. I'm not updating the changes file nor the spec because this version 3.1.37.1 is not submitted to IBS yet (so this fix willl be included in that version).
=> Add some missing elements to AutoYaST schema

package/yast2-users.changes, src/autoyast-rnc/users.rnc
Fixes [bsc#954412](https://bugzilla.suse.com/show_bug.cgi?id=954412) for SLE 12 SP1. BTW, `SLE-12-GA` branch is merged into `sle-12-sp1-after_release`.
=> Fix AutoYaST schema in SLE 12 SP1

package/yast2-users.changes, package/yast2-users.spec, src/autoyast-rnc/users.rnc
Merge SLE12 SP1 after release changes into SLE-12-SP1 to be released as a MU.
=> Merge post SLE 12 SP1 release changes

Rakefile, package/yast2-users.changes, package/yast2-users.spec, src/autoyast-rnc/users.rnc
Merge `SLE-12-SP1` branch into `master`.
=> Merge SLE 12 SP1 into master

package/yast2-users.changes, package/yast2-users.spec, src/modules/UsersRoutines.pm
Please review the following changes:
* 5361e67 packaging
* c96224b checking for empty string
=> [Review] Request from 'schubi2' @ 'yast/yast-users/review_160218_checking_empty_string'

package/yast2-users.changes, package/yast2-users.spec, src/modules/UsersRoutines.pm
This is a backport from master
=> backport from master

package/yast2-users.changes, package/yast2-users.spec, src/modules/Users.pm
Merge `SLE-12-SP1` branch into `master` to fix [bnc#965852](https://bugzilla.suse.com/show_bug.cgi?id=965852).
=> Merge SLE 12 SP1

package/yast2-users.changes, package/yast2-users.spec, src/modules/Users.pm
Fix for [bsc#980878](https://bugzilla.suse.com/show_bug.cgi?id=980878).
=> Fix CheckHomeMounted during 1st stage

package/yast2-users.changes, package/yast2-users.spec, src/modules/Users.pm
Fixes concatenation with Perl strict mode.
=> Fix check home mounted concat

package/yast2-users.changes, package/yast2-users.spec, src/lib/users/dialogs/inst_user_first.rb
Fixes [bsc#986542](https://bugzilla.suse.com/show_bug.cgi?id=986542).
=> Fix first user creation during installation

package/yast2-users.changes, package/yast2-users.spec, src/clients/users_auto.rb, test/fixtures/users_error.yml, test/test_helper.rb, test/users_auto_test.rb
Please review the following changes:
* 524cc9a packaging
* a1a7a69 checking defined users in AutoYaST profile
=> [Review] Request from 'schubi2' @ 'yast/yast-users/review_160830_checking_user_entries_in_autoyast'

Rakefile, package/yast2-users.changes, package/yast2-users.spec, src/clients/users_auto.rb, test/fixtures/users_no_error.yml, test/users_auto_test.rb
Please review the following changes:
* 76b7bcb Merge pull request #110 from yast/bug_996823_SP2
=> [Review] Request from 'schubi2' @ 'yast/yast-users/review_160902_bug_996823_master'

package/yast2-users.changes, package/yast2-users.spec, src/include/users/widgets.rb
=> Master fix of  bug#1000749 into master

package/yast2-users.changes
See https://ci.opensuse.org/view/Yast/job/yast-users-master/132/console
=> Fix changelog timestamps

Rakefile, package/yast2-users.changes, package/yast2-users.spec
Merge `merge_after_SP2_release` branch into `SLE-12-SP2`.
=> SLE 12 SP2 merge

package/yast2-users.changes, package/yast2-users.spec, src/Makefile.am, src/lib/users/dialogs/inst_root_first.rb, src/lib/users/widgets.rb, test/Makefile.am, test/widgets_test.rb
tested manually that it keep working in common installation
=> Reusable root widget

package/yast2-users.changes, package/yast2-users.spec, src/Makefile.am, src/lib/users/dialogs/inst_root_first.rb, src/lib/users/widgets.rb, test/Makefile.am, test/widgets_test.rb
just port of change to CASP #126
=> Root widget master

package/yast2-users.changes, package/yast2-users.spec, src/lib/users/dialogs/inst_root_first.rb, src/lib/users/widgets.rb, test/widgets_test.rb
=> Users::PasswordWidget: allow horizontal layout (FATE#322328) (CASP->master)

package/yast2-users.changes, package/yast2-users.spec, src/modules/Users.pm, src/modules/UsersPasswd.pm
- [Trello Card](https://trello.com/c/H5k6VobD/1260-3-mu-sle-12-authorized-keys-ay-need-to-work-for-all-users-including-root)
=> AutoYaST: Write & Export SSH Authorized keys for root (bsc#1066342)

package/yast2-users.changes, package/yast2-users.spec, src/modules/Users.pm, src/modules/UsersPasswd.pm
=> Merge SLE-12-SP3 into master

.coveralls.yml, .gitignore, .travis.yml, .yardopts, package/yast2-users.changes, package/yast2-users.spec, src/include/users/dialogs.rb, test/Makefile.am, test/dialogs_test.rb, test/users_auto_test.rb
Merging #153 to master
plus some minimal refactoring of the affected method, which had 1900 lines. And the obviously correct refactoring obviously introduced a stupid bug which I found with manual testing.
Plus Coveralls and Yardoc.
=> Fixed removing the password expiration date

package/yast2-users.changes, package/yast2-users.spec, src/modules/Users.pm, test/users_auto_test.rb
=> Do not crash if root is not defined

package/yast2-users.changes, package/yast2-users.spec, src/modules/Users.pm
This PR is a backport of #156.
=> Root password

package/yast2-users.changes, package/yast2-users.spec
sle12-sp4 has diverged already
=> fix version number and release 3.2.15.1

src/include/users/dialogs.rb
Fixing some typos, mostly in comments in dialogs.rb
=> Fix_Typos_In_Comments

package/yast2-users.changes, package/yast2-users.spec, src/lib/users/widgets/public_key_selector.rb
Clarify whether the removable device should be connected during the whole installation.
=> Improve public selector help text

src/lib/users/ssh_authorized_keyring.rb
Not a biggie, but fix a typo in a comment
=> Fix Minor Typo

package/yast2-users.spec
=> Minor typo in comment

src/lib/users/widgets/public_key_selector.rb
Okay, if you are going to do it, then get ALL the typos, please, Gerry!
=> Edit comments

.rubocop.yml, .travis.yml, Rakefile, package/yast2-users.changes, package/yast2-users.spec, src/include/users/routines.rb, src/lib/users/ca_password_validator.rb, src/lib/users/clients/users_finish.rb, src/lib/users/dialogs/encryption_method.rb, src/lib/users/dialogs/inst_user_first.rb, src/lib/users/dialogs/users_to_import.rb, src/lib/users/encryption_method.rb, src/lib/users/encryption_proposal.rb, src/lib/users/proposal.rb, src/lib/users/ssh_authorized_keyring.rb, src/lib/users/ssh_authorized_keys_file.rb, src/lib/users/ssh_public_key.rb, src/lib/users/users_database.rb, src/lib/users/widgets.rb, src/lib/users/widgets/public_key_selector.rb, src/modules/UsersUI.rb, test/dialogs_test.rb, test/lib/users/ca_password_validator_test.rb, test/lib/users/encryption_method_test.rb, test/lib/users/leaf_blk_device_test.rb, test/lib/users/local_password_test.rb, test/lib/users/ssh_authorized_keyring_test.rb, test/users_auto_test.rb, test/users_test.rb, test/widgets_test.rb
Add Rubocop support and fixes the package version which already diverged from SLE-15-GA.
=> Rubocop and documentation fixes + Version fix

Dockerfile, package/yast2-users.changes, package/yast2-users.spec, src/modules/UsersPasswd.pm, src/modules/UsersPluginKerberos.pm, src/modules/UsersPluginQuota.pm, src/modules/UsersSimple.pm, src/modules/YaPI/USERS.pm
=> Fix syntax

package/yast2-users.changes
=> fixed bugzilla number

package/yast2-users.changes, package/yast2-users.spec, src/autoyast-rnc/users.rnc, src/modules/UsersRoutines.pm
> - Added tag home_btrfs_subvolume to *.rnc file (bsc#1128707)
> - Improved error message layout while creating btrfs subvolumes.
=> added home_btrfs_subvolume tag

package/yast2-users.changes, package/yast2-users.spec, src/modules/Users.pm
This is Steffen's PR:
https://github.com/yast/yast-users/pull/202/files
I have added the package stuff and have tested it again.
=> Improved checking of already existing home

Dockerfile, package/yast2-users.changes, package/yast2-users.spec, src/modules/Users.pm
It merges #214 
> Do not copy the skeleton files for system users
---
Other related PRs:
* #202 - don't copy skel files for system users
* #211 - Fix Dockerfile
=> Merge SLE-12-SP2 into SLE-12-SP3

package/yast2-users.changes, package/yast2-users.spec, src/modules/Users.pm
See https://github.com/yast/yast-yast2/pull/988.
=> Read login.defs settings from /usr/etc

package/yast2-users.changes, package/yast2-users.spec, src/desktop/org.opensuse.yast.Users.desktop
related PR: yast/yast-yast2#1020
=> Wsl whitelist

package/yast2-users.changes, package/yast2-users.spec, src/lib/users/proposal.rb
Problem
========
* Showing AY user settings in the proposal screen crashed when the user would like to change it.
* The regarding UI does not fit to the settings of the AY configuration file.
Solution
=======
* Fixed crash
* Only showing the settings. The user cannot change it.
=> Fixed crash in AY user proposal

.travis.yml, package/yast2-users.changes, package/yast2-users.spec, src/autoyast-rnc/users.rnc
trello: https://trello.com/c/HkFkUQHj/1791-3-continue-with-new-xml-parser-xml-validation
depends on yast/yast-autoinstallation#598
Agreed to postpone for now that trang and jing travis validation to not delay even more new xml parser.
bsc: https://bugzilla.suse.com/show_bug.cgi?id=1170886
=> Schema change

src/lib/y2users/linux.rb, src/lib/y2users/linux/writer.rb, test/lib/y2users/linux/writer_test.rb, test/lib/y2users/test_helper.rb
We are developing a writer that commits the changes to the real system. This PR includes the skeleton (that is, the right files in the right places) with no real functionality. It also includes some documentation and details about the future implementation.
=> WIP: skeleton of the Y2Users::Linux writer

src/lib/y2users/config.rb, src/lib/y2users/password.rb, src/lib/y2users/user.rb, test/lib/y2users/config_element_examples.rb, test/lib/y2users/config_test.rb, test/lib/y2users/group_test.rb, test/lib/y2users/password_test.rb, test/lib/y2users/user_test.rb
API of `Y2Users` classes was re-designed, but unit tests were still missing.
Add unit tests and fix some issues.
=> Unit tests

src/lib/y2users/linux/local_reader.rb, src/lib/y2users/linux/reader.rb, src/lib/y2users/parsers/group.rb, src/lib/y2users/parsers/passwd.rb, src/lib/y2users/parsers/shadow.rb, test/lib/y2users/linux/local_reader_test.rb, test/lib/y2users/linux/reader_test.rb
goal is to have Local reader that can read from target directory ( used when importing users ) and it can be also used for getent reader to distinguish between local and remote users.
=> Add Local reader and separate parsers

src/lib/y2users/linux/writer.rb
See https://trello.com/c/Dii9k51f/2467-2-ensure-consistency-of-caches
This replaces #279
=> Document why nscd and NIS are not longer refreshed

src/lib/y2users/linux/writer.rb
Using "users" (the right one) instead of "y2users".
=> Fix the textdomain

src/lib/users/clients/auto.rb, test/lib/users/clients/auto_test.rb, test/lib/y2users/autoinst/reader_test.rb
trello: https://trello.com/c/CT6tRt83/2484-1-autoyast-read-root-password-from-booting-command-line
tested beside unit tests also manually
=> Y2users linuxrc root pwd

src/Makefile.am, src/lib/y2users/linux/groups_writer.rb, src/lib/y2users/linux/login_config_writer.rb, src/lib/y2users/linux/useradd_config_writer.rb, src/lib/y2users/linux/users_writer.rb, src/lib/y2users/linux/writer.rb, test/lib/y2users/linux/writer_test.rb
Small fixes extracted from https://github.com/yast/yast-users/pull/298, now that we have decided to not implement what was included in that pull request.
All commits were already reviewed in the other pull request.
=> Several small fixes

package/yast2-users.changes, package/yast2-users.spec, src/desktop/org.opensuse.yast.Users.desktop
=> bsc#1187270: fix control center tooltip

package/yast2-users.changes, package/yast2-users.spec, src/desktop/org.opensuse.yast.Users.desktop
=>  bsc#118727: fix control center tooltip

src/lib/y2users/config_merger.rb, src/lib/y2users/group.rb, test/lib/y2users/group_test.rb
Fixing a bug found during manual testing of the AutoYaST installation... and adding the debug information that leaded me to finding the problem.
=> Small fixes 

package/yast2-users.spec, src/lib/users/clients/auto.rb, src/lib/users/clients/users_finish.rb, src/lib/y2users/password_helper.rb, src/lib/y2users/password_validator.rb, src/lib/y2users/user_validator.rb, test/lib/users/clients/auto_test.rb, test/lib/y2users/password_helper_test.rb, test/lib/y2users/user_validator_test.rb, test/users_finish_test.rb
Depends on https://github.com/yast/yast-yast2/pull/1178, tests will not pass until that is merged
Manually tested together with the changes in yast2. See the other pull request for screenshots.
=> Use Y2Issues.report in users_finish

package/yast2-users.changes, package/yast2-users.spec, src/desktop/org.opensuse.yast.Users.desktop
Version bump and changelog just before the big merge into master.
This includes also a merge of the master branch into y2users, to incorporate some changes done in that branch during the y2users development.
=> Version and changelog

package/yast2-users.changes, package/yast2-users.spec, src/modules/Users.pm
See https://github.com/yast/yast-users/pull/317.
=> Port PR#317 to master

src/lib/y2users/users_module/reader.rb, src/modules/Users.pm, test/lib/y2users/users_module/reader_test.rb
=> Add reader from Users module

src/Makefile.am, test/Makefile.am
New files were not added to their corresponding Makefile, see:
* https://github.com/yast/yast-users/pull/329
* https://github.com/yast/yast-users/pull/328
=> Add missing files to makefiles

src/modules/Users.pm
Delete variables that are not needed after #333
=> Some cleanup related to useradd and groupadd

package/yast2-users.changes
Introduced by mistake in https://github.com/yast/yast-users/pull/348
=> Fix wrong bug reference in changes file

package/yast2-users.changes, package/yast2-users.spec, src/lib/users/dialogs/inst_user_first.rb, src/lib/y2users/group.rb, test/lib/users/dialogs/inst_user_first_test.rb
- Fix import users: do not fail if the group does not exist
- https://bugzilla.suse.com/show_bug.cgi?id=1197040
=> Fix import users

package/yast2-users.changes, package/yast2-users.spec, src/lib/y2users/linux/users_writer.rb, test/lib/y2users/linux/users_writer_test.rb
merge to master of https://github.com/yast/yast-users/pull/368
=> User nohome master

package/yast2-users.changes, package/yast2-users.spec, src/lib/y2users/home.rb, src/lib/y2users/linux/create_user_action.rb, src/modules/Users.pm, test/lib/y2users/home_test.rb, test/lib/y2users/linux/create_user_action_test.rb
Merge of #376 (which fixes [bsc#1209377](https://bugzilla.suse.com/show_bug.cgi?id=1209377)), into master.
As explained at #377 (see details there) this also includes other fixes that were not properly merged to modern branches in the past.
=> Stop mangling btrfs_subvolume as boolean at Users.EditUser

package/yast2-users.changes, package/yast2-users.spec, src/lib/users/clients/auto.rb, test/lib/users/clients/auto_test.rb
=> Write users when running AutoYaST on an installed system

package/yast2-users.changes, package/yast2-users.spec, src/lib/users/dialogs/inst_user_first.rb
see https://github.com/yast/yast-users/pull/383
=> Merged SLE-15-SP5 branch

package/yast2-users.changes, package/yast2-users.spec, src/lib/users/ssh_authorized_keyring.rb, src/lib/users/ssh_authorized_keys_file.rb, src/lib/y2users/linux/reader.rb, src/lib/y2users/linux/set_auth_keys_action.rb, src/modules/SSHAuthorizedKeys.rb, test/lib/users/ssh_authorized_keyring_test.rb, test/lib/users/ssh_authorized_keys_file_test.rb, test/lib/y2users/linux/set_auth_keys_action_test.rb, test/ssh_authorized_keys_test.rb
see https://github.com/yast/yast-users/issues/396
Backport commits from master from pull request https://github.com/yast/yast-users/pull/382
- All tests now passes ( failed before backport )
=> Backport namespace fix sp6

package/yast2-users.changes
Add the version to the changes file (forgot it on #404).
=> Add version to changes file
