yast/yast-users

- package/yast2-users.changes
- package/yast2-users.spec
- src/modules/Users.pm
This is a port of #79 and fixes [bsc#928607](https://bugzilla.suse.com/show_bug.cgi?id=928607) for openSUSE 13.2. Manually tested.
> Port of bugfix for boo#982607 to openSUSE 13.2

- package/yast2-users.changes
- package/yast2-users.spec
- src/modules/Users.pm
This patch fixes users import during autoinstallation. It's related to [bsc#965852](https://bugzilla.suse.com/show_bug.cgi?id=965852).
The original problem is that before doing the import, all local users (inst-sys users) were read, so inst-sys users where merged with imported ones. In this stage, we should ignore inst-sys users. That's not a problem during autoupgrade, as long as users are not modified/created in that scenario.
> Fix users import

- package/yast2-users.changes
- package/yast2-users.spec
- src/modules/UsersSimple.pm
* Fixes [bsc#978648](https://bugzilla.suse.com/show_bug.cgi?id=978648).
> Fix users import when an entry in /etc/shadow is missing

- package/yast2-users.changes
- package/yast2-users.spec
- src/autoyast-rnc/users.rnc
- src/lib/users/ssh_authorized_keyring.rb
- src/lib/users/ssh_authorized_keys_file.rb
- src/modules/SSHAuthorizedKeys.rb
- test/lib/users/ssh_authorized_keyring_test.rb
- test/lib/users/ssh_authorized_keys_file_test.rb
- test/ssh_authorized_keys_test.rb
Fix a potential security issue in #113 (writing to authorized_keys when it's not a file).
> Don't write authorized_keys if it's not  a regular file

- .travis.yml
- package/yast2-users.changes
- package/yast2-users.spec
- src/modules/UsersLDAP.pm
- testsuite/modules/Ldap.rb
- testsuite/tests/ConvertMap.out
- testsuite/tests/ConvertMap.rb
[bsc#999203](https://bugzilla.suse.com/show_bug.cgi?id=999203)
Most importantly, this breaks the critical path link between yast2-users and yast2-network (users no longer BuildRequire ldap which Requires network)
Total build time for this package on my machine decreases from 69s to 63s
The number of buildrequired packages decreases from 255 to 227:
```
[    2s] deleting curl
[    2s] deleting device-mapper
[    2s] deleting elfutils
[    2s] deleting libaio1
[    2s] deleting libasm1
[    2s] deleting libdevmapper-event1_03
[    2s] deleting libdevmapper1_03
[    2s] deleting libdw1
[    2s] deleting libldapcpp1
[    2s] deleting libmetalink3
[    2s] deleting libparted0
[    3s] deleting libstorage-ruby
[    3s] deleting libstorage7
[    3s] deleting lsscsi
[    3s] deleting parted
[ …
```
> Speedup build

- package/yast2-users.changes
- package/yast2-users.spec
I need to do this in order to create a consistent `merge_after_SP2_release` branch.
And please remember that changes introduced only in master should make numbers jump to 3.2.
> Fix version numbers to make maintenance possible

- package/yast2-users.changes
- package/yast2-users.spec
- src/include/users/widgets.rb
Bump version to 3.1.62 for bsc#1000749.
Replaces #117
> Fix the invocation of authentication configuration instance.

- package/yast2-users.changes
- package/yast2-users.spec
- src/lib/users/dialogs/inst_root_first.rb
- src/lib/users/widgets.rb
- test/widgets_test.rb
- https://github.com/yast/yast-installation/pull/487
- https://fate.suse.com/322328
If `little_space` is `false` (the default), the widget will use a vertical layout, and include a "don't forget this" label.
If `little_space` is `true`, the helpful label is omitted
Also, do not steal the keyboard focus: originally we put it in so that openQA can start typing the password right away, but the layout will work differently in the CaaSP all-in-one dialog so we need a way to disable it.
~~TODO: version, changes, dependencies~~
> Users::PasswordWidget: allow horizontal layout (FATE#322328)

- package/yast2-users.changes
- package/yast2-users.spec
- src/include/users/dialogs.rb
[bsc#1080125](https://bugzilla.suse.com/show_bug.cgi?id=1080125)
a former L3, the PTF was validated by the customer
> Fixed removing the password expiration date

- package/yast2-users.changes
- package/yast2-users.spec
- src/modules/Users.pm
version that works for my testing as alternative for #155 
tested manually with users and without users in autoyast profile and in the end also testing customer case where he specify for root defaults, but without password and have there encrypted false which result in his problem.
> Root password

- src/modules/Users.pm
The old code would encrypt the password twice. Use the plain password in
this place.
> fix setting root password via RootPassword boot option (bsc#1081958)

- package/yast2-users.changes
- package/yast2-users.spec
- src/modules/UsersPasswd.pm
When working with NIS 'root' is typically not included.
> read ssh keys from root user only if the user exists (bsc#1112119, bsc#1107456)

- package/yast2-users.changes
- src/modules/Users.pm
This is a backport of https://github.com/yast/yast-users/pull/156.
> Fix import of RootPassword if user is specified in autoyast profile (bsc#1081958)

- package/yast2-users.changes
- package/yast2-users.spec
- src/lib/users/dialogs/inst_user_first.rb
https://trello.com/c/PAVZthmL
Skip creating a first local user during installation if `enable_local_user` is set to `false` in the `global` section in `control.xml`.
```XML
<system_role>
<id>sample_role</id>
<globals>
<enable_local_users config:type="boolean">false</enable_local_users>
</globals>
<software>
<default_patterns>x11 base</default_patterns>
</software>
<order config:type="integer">123</order>
</system_role>
```
There is one challenge when going back and forth in the workflow and changing the system role between one that allows to create local users and another that does not: 
If at first a role is chosen that does allow local users **and** the user even leaves the "use this password for root" checkbox checked (which is the default), we need to make sure that both things are …
> Allow system role to default to no local user

- Dockerfile
- package/yast2-users.changes
- package/yast2-users.spec
- src/lib/users/dialogs/inst_user_first.rb
https://trello.com/c/VVM2ib4G/
https://bugzilla.suse.com/show_bug.cgi?id=1128385 (openSUSE)
https://bugzilla.suse.com/show_bug.cgi?id=1060173 (SLES)
https://github.com/yast/yast-pam/pull/13
During installation and later in the installed system, "autologin" is offered even if it doesn't make sense and if it can't even work: If a user selects the "server" role or some other package combination that does not provide X11 or Wayland or, in general, a graphical login, the "Autologin" checkbox is available.
Selecting that option has no effect in that case.
Don't only rely on the control.xml file that has a parameter if that should be offered at all; also check if the capability is available, i.e. if a display manager (login manager) that supports that feature is or will be installed. …
> Offer autologin only if a display manager that supports it is installed

- package/yast2-users.changes
- package/yast2-users.spec
- src/modules/Users.pm
The user creation does not respect the desired behavior: to create the user's home as a plain directory (default) or as a Btrfs subvolume (ticking the "Create as Btrfs Subvolume" option added in 4.1.7). Instead, it is **always** - in an installed system - trying to create a Btrfs subvolume (unsuccessfully when the chosen path is no in a Btrfs filesystem).
- https://bugzilla.suse.com/show_bug.cgi?id=1134970
- https://trello.com/c/GuqA45nj
- Related to https://github.com/yast/yast-users/pull/195
Simply because Perl understands the `Yast::YCP::Boolean` as a _true thing_ even when its `->value()` is `false`. That's the reason why it must be used the `bool` subroutine, which returns the right value. 
To initialize the `$use_btrfs_subvolume"`variable properly, using the `bool` subroutine …
> Fix the user's home creation [bsc#1134970]

- package/yast2-users.changes
- package/yast2-users.spec
- src/modules/Users.pm
PR to sync changes introduced in #206 
> **Problem**
>
> The user creation does not respect the desired behavior: to create the user's home as a plain directory (default) or as a Btrfs subvolume (ticking the "Create as Btrfs Subvolume" option added in 4.1.7). Instead, it is always - in an installed system - trying to create a Btrfs subvolume (unsuccessfully when the chosen path is no in a Btrfs filesystem).
>
>    https://bugzilla.suse.com/show_bug.cgi?id=1134970
>    https://trello.com/c/GuqA45nj
>    Related to #195
> **Solution**
> 
> To initialize the $use_btrfs_subvolume"variable properly, using the bool subroutine mentioned above.
> Merge SLE-15-SP1 into master

- package/yast2-users.changes
- package/yast2-users.spec
- src/modules/Users.pm
- testsuite/tests/EditUser.out
- testsuite/tests/YaPIGroupAdd.out
- Failing old test suite
```
[   92s]  Write	.target.string "/etc/shadow" "at:!:13636:0:99999:7:::\nbin:*:13636::::::\ndaemon:*:13636::::::\nmail:*:13636::::::\nnobody:*:13636::::::\nroot:password:13636::::::\nuucp:*:13636::::::\nhh:heslo:13727:0:99999:7:::\n+::0:0:0::::\n" true
[   92s] -Execute	.target.bash "/usr/sbin/nscd -i passwd" 0
[   92s]  Return
```
- It turned out that it depends whether the `nscd` package is installed during the RPM build or not
- Check `Mode.test` and do not check for the package presence in that case
- 4.2.3
> Fixed unit test: skip Package::Installed() call (bsc#1138668)

- package/yast2-users.changes
- package/yast2-users.spec
- src/modules/Users.pm
https://bugzilla.suse.com/show_bug.cgi?id=1141017
User password shows up in log.
Hide all password fields: `text_userpassword` and `userPassword`.
> hide all password fields in log (bsc#1141017)

- package/yast2-users.changes
- package/yast2-users.spec
- src/modules/Users.pm
The user password is being leak in the YaST logs from `4.1.12`.
Do not log the password (backport of https://github.com/yast/yast-users/pull/210)
Tested manually via DUD, the password is now hidden.
```
linux-qotp:~ # zgrep text_ /var/log/YaST2/*
/var/log/YaST2/y2log-1.gz:  'text_userpassword' => '*****',
/var/log/YaST2/yast-installation-logs.tar.xz:Binary file (standard input) matches
```
---
Related to https://github.com/yast/yast-users/pull/202, https://github.com/yast/yast-users/pull/203, and https://github.com/yast/yast-users/pull/210
> [Backport] Do not log passwords

- Dockerfile
- package/yast2-users.changes
- package/yast2-users.spec
- src/modules/Users.pm
AutoYaST is copying the skeleton files for imported system users.
Replicate some [logic already available in the `AddUser()` subroutine](https://github.com/yast/yast-users/blob/ab9ee6011240adeebbfab72230d32502a02a03c4/src/modules/Users.pm#L3111-L3113), which is not used for the AutoYaST imported users.
> A fix originally proposed for SLE-15[1][2] to solve bsc#1130158 and now
> backported to SLE-12 to solve bsc#1143205.
> 
> [1] https://github.com/yast/yast-users/pull/202
> [2] https://github.com/yast/yast-users/pull/202/commits/937fe2b9b1abd95f7b4bec9eafd40089236f1949
* Tested manually, via _dud_
<p align="center">The <em>pulseaudio</em> directory is empty, as expected</p>
> Do not copy the skeleton files for system users

- Dockerfile
- package/yast2-users.changes
- package/yast2-users.spec
- src/modules/Users.pm
It merges #214 
> Do not copy the skeleton files for system users
---
Other related PRs:
* #202 - don't copy skel files for system users
* #211 - Fix Dockerfile
* #215 - Merge SLE-12-SP2 into SLE-12-SP3
> Merge SLE-12-SP3 into SLE-12-SP4

- Dockerfile
- package/yast2-users.changes
- package/yast2-users.spec
- src/modules/Users.pm
It merges #214 
> Do not copy the skeleton files for system users
---
Other related PRs:
* #202 - don't copy skel files for system users
* #211 - Fix Dockerfile
* #215 - Merge SLE-12-SP2 into SLE-12-SP3
* #216 - Merge SLE-12-SP3 into SLE-12-SP4
> Merge SLE-12-SP4 into SLE-12-SP5

- package/yast2-users.changes
- package/yast2-users.spec
- src/lib/users/dialogs/inst_root_first.rb
- test/lib/users/dialogs/inst_root_first_test.rb
During an installation or firstboot configuration, the dialog for setting the root password abort immediately when  the `Abort` button is pressed. It should request an abort confirmation before abort.
- https://trello.com/c/xZvv9fNN/1698-leap152-p3-1165506-installer-obeys-the-abort-button-without-any-confirmation-only-when-on-roots-password-screen
- https://bugzilla.suse.com/show_bug.cgi?id=1165506
Added the popup for confirming the abort.
> Request confirmation for aborting in the root password dialog

- package/yast2-users.changes
- package/yast2-users.spec
- src/modules/UsersPluginKerberos.pm
The package *krb5* was adapted to provide binaries at */usr/sbin* path instead of */usr/lib/mit/sbin*, see https://build.opensuse.org/request/show/814662.
YaST is still using the old */usr/lib/mit/sbin* paths. 
* https://trello.com/c/PxH6LJhf/1951-3-new-krb5-path-in-tw
* https://bugzilla.opensuse.org/show_bug.cgi?id=1174078
Adapt YaST code to use the new paths.
Note: the changes in the *kbr5* package were done without a change in the version number, so *yast2-users* cannot indicate a conflict with any *kbr5* old version. And also note that this new *yast2-users* package will be submitted to both: SLE-15-SP3 and Factory, but most likely SLE-15-SP3 will not receive any update for *kbr5*. Because that, *yast2-users* has to deal with both possible paths (/usr/lib/mit/sbin and /usr/sbin).
> Use new krb5 sbin path 

- package/yast2-users.changes
- package/yast2-users.spec
- src/modules/Users.pm
The old SCR nsswitch agent has been replaced by a CFA class able to deal with the new layout having the configuration split between `/usr/etc` and `/etc.` See https://github.com/yast/yast-pam/pull/20 for more details.
Start using the [yast2-pam/Nsswitch module](https://github.com/yast/yast-pam/blob/43201e3ed0d50f8dce3a853aef3057265d8aa471/src/modules/Nsswitch.rb) instead of the no longer available SCR agent.
* **Not unit testing** for the complex Perl module.
* Tested manually running.
> Use yast2-pam/Nsswitch module to read NSS configuration

- package/yast2-users.changes
- package/yast2-users.spec
- src/lib/users/leaf_blk_device.rb
- src/lib/users/widgets/public_key_selector.rb
- test/fixtures/lsblk.txt
- test/lib/users/leaf_blk_device_test.rb
- test/lib/users/widgets/public_key_selector_test.rb
It is allowed to use any device that contains a filesystem if such a filesystem is not squashfs (which is basically used by the installer). It should fix [bsc#1178509](https://bugzilla.suse.com/show_bug.cgi?id=1178509).
> Public key selector: filter is based on filesystems

- package/yast2-users.changes
- package/yast2-users.spec
- src/lib/users/clients/auto.rb
- test/lib/users/clients/auto_test.rb
bsc: https://bugzilla.suse.com/show_bug.cgi?id=1184216
Missing reset method result in calling abstract method that lead to exception.
> Fix auto users reset

- package/yast2-users.changes
- package/yast2-users.spec
- src/modules/Users.pm
- src/modules/UsersLDAP.pm
- src/modules/UsersRoutines.pm
*yast-users* does not use the *useradd* command for creating a new user. Instead of that, it does all the work by its own (create home directory, adapt permissions, set password, etc). One of the steps performed by *yast-users* is to execute the *useradd.local* script. That script was taking care of copying the content of */usr/etc/skel* into the new created home directory. But *useradd.local* does not do it anymore. Such a logic was moved to *useradd* in the *shadow* suite.  So now, when a new user is created with *yast-users*, the content of */usr/etc/skel* is not copied at all, resulting on incomplete home directories. 
That missing files in the new home directories is blocking the lastest changes for the *shadow* suite in Factory (including the management of */usr/etc/skel* directly …
> Copy skel from usr

- .coveralls.yml
- Not needed anymore with the new GitHub Actions
> Removed .coveralls.yml

- src/lib/y2user/configuration.rb
- src/lib/y2user/group.rb
- src/lib/y2user/password.rb
- src/lib/y2user/readers/getent.rb
- src/lib/y2user/readers/users_simple.rb
- src/lib/y2user/user.rb
Some new classes are being developed in order to read and write users and groups. Initially, it was decided to put that classes in the *yast2* module. The idea was to avoid the *yast2-users* dependency from [other YaST modules](https://github.com/yast/yast-users-ng/blob/master/doc/known_API_usage.md) which need to read the list of users. But that decision was re-evaluated because currently there is no problem with such a dependency of *yast2-users*. Moreover, placing that classes in *yast2* presents other problems:
* Makes organization of classes less clear, because part is in *yast2* and other part in *yast-users*.
* Could add unnecessary dependencies to *yast2* (e.g., homed). 
This PR copies the current *y2users* code from *yast2*.
> Copy code from yast2

- src/lib/y2users/linux/writer.rb
- src/lib/y2users/user.rb
- test/lib/y2users/linux/writer_test.rb
This is a follow-up of #247. It starts adding functionality in Y2Users::Linux::Writer, making use of [`useradd`](https://man7.org/linux/man-pages/man8/useradd.8.htmlhttps://man7.org/linux/man-pages/man8/useradd.8.html) and [`chpasswd`](https://man7.org/linux/man-pages/man8/chpasswd.8.html) commands.
It adds basic unit tests too, but it's expected to improve them (see #249)
> Linux writer implementation

- src/lib/y2users/linux/writer.rb
- src/lib/y2users/user.rb
- test/lib/y2users/linux/writer_test.rb
With this, the Linux writer always tries to create the home directory for normal users, but not for system ones. We agreed that should be the expected behavior.
This also improves a bit some of the existing tests of the Linux writer (for example, making sure the `chpasswd` command does not reveal too much).
> Create home directory and distinguish system users

- .editorconfig
- src/lib/y2users.rb
- src/lib/y2users/users_simple/writer.rb
- test/lib/y2users/users_simple/writer_test.rb
During the installation, we plan to create new *Y2Users::User* objects as result of the users forms. But we need to save the users information into the *UsersSimple* module because several reason:
* As a way of saving the users data for recovering it later when the users are going to be created in the system.
* As a way of ensuring that other modules can still access to the users data from *UsersSimple*, as they could be doing now.
Added new writer (*Y2Users::UsersSimple::Writer*) that stores information from *Y2Users::User* objects into the *UsersSimple* module.
NOTES:
* *Y2Users::Password* contains an encrypted password, but *UsersSimple* expects a plain password. Maybe,  *Y2Users::Password* should store a plain password too.
* *UsersSimple* has some separate attributes in order to save …
> Add UsersSimple writer

- src/lib/y2users/user.rb
- src/lib/y2users/users_simple.rb
- src/lib/y2users/users_simple/writer.rb
- test/lib/y2users/users_simple/writer_test.rb
*UsersSimple* module is not expected to include the *root* user in its list of users. But *Y2Users::UsersSimple::Writer* is not excluding the root user when writing users into *UsersSimple*.
*Y2Users::UsersSimple::Writer* does not store *root* user anymore. But it uses the *UsersSimple* API to store root related info like the password.
> UsersSimple Writer: manage root user info

- src/lib/y2users/linux/writer.rb
- test/lib/y2users/linux/writer_test.rb
Following with  `Y2Users::Linux::Writer` implementation (see #247, #249, and #250), now it 
* receives the _initial configuration_, and
* only creates new users or modifies passwords of existing ones
> [Y2Users::Linux::Writer] Creates only new users

- src/lib/y2users/config.rb
- src/lib/y2users/config_element.rb
- src/lib/y2users/group.rb
- src/lib/y2users/password.rb
- src/lib/y2users/user.rb
Initial API was designed with immutability concept in mind. Then, it was decided to follow a more classical approach,  see https://github.com/yast/yast-users/issues/257.
API was modified as previously agreed.
NOTE: unit tests for `Config`, `User`, `Group` and `Password` will come with a separate PR. And the same for adapting the current readers/writers unit tests.
> API changes

- src/lib/y2users/config_manager.rb
- src/lib/y2users/linux/reader.rb
- src/lib/y2users/linux/writer.rb
- src/lib/y2users/users_simple/reader.rb
- src/lib/y2users/users_simple/writer.rb
- test/lib/y2users/linux/writer_test.rb
- test/lib/y2users/users_simple/writer_test.rb
Readers and writers for `Y2Users::Linux` and `Y2Users::UsersSimple` got updated after migrating to the new API.
Adapt readers and writers to the new API.
> Adapt readers and writers to use the new API

- src/Makefile.am
- src/lib/users/ca_password_validator.rb
- src/lib/users/dialogs/inst_user_first.rb
- src/lib/users/widgets.rb
- src/lib/y2users.rb
- src/lib/y2users/help_texts.rb
- src/lib/y2users/password_validator.rb
- src/lib/y2users/user.rb
- src/lib/y2users/user_validator.rb
- src/lib/y2users/validation_config.rb
- test/lib/users/ca_password_validator_test.rb
- test/lib/users/local_password_test.rb
- test/lib/y2users/help_texts_test.rb
- test/lib/y2users/validation_config_test.rb
Part of https://trello.com/c/nFDiHYCU/2415-validation-of-the-new-user-with-a-better-api
Included:
- Fixed `Y2Users::UsersSimple::Reader`
- Adapted the InstUserFirst dialog to:
- When the dialog opens:
- Load the information from `UserSimple` into `Y2User` objects (using the fixed reader)
- Preload the form with the information from those objects
- When the user click "next"
- Update the `Y2User` objects with the information entered by the user
- Check objects with the new `Y2User` validators, reporting `Y2Issues::Issues` to the user
- Write the information in the `Y2Users` objects back to `UserSimple` if the objects are valid
- Small reorganization of the code that generates the help texts
- Better sharing between several dialogs with no direct dependency on `UsersSimple`
- Allowed to …
> Adaptation of Dialogs::InstUserFirst to use Y2Users

- src/Makefile.am
- src/lib/users/dialogs/inst_user_first.rb
- src/lib/users/widgets.rb
- src/lib/y2users/inst_users_dialog_helper.rb
- test/lib/y2users/password_validator_test.rb
- test/widgets_test.rb
Related to 
* Trello card (internal link): https://trello.com/c/dsDBpo7B/
* Previous PR: https://github.com/yast/yast-users/pull/261
It adapts the `Users::PasswordWidget`, used by _inst\_root\_first_ dialog and widget, to rely on Y2Users objects instead of keep using Yast::UsersSimple directly. 
It has been tested manually, apart to adapt the existent unit tests too.
> Adapt Users::PasswordWidget to use Y2Users

- src/Makefile.am
- src/lib/y2users/config.rb
- src/lib/y2users/config_merger.rb
- src/lib/y2users/group.rb
- src/lib/y2users/password.rb
- src/lib/y2users/user.rb
- test/Makefile.am
- test/lib/y2users/config_merger_test.rb
- test/lib/y2users/config_test.rb
- test/lib/y2users/group_test.rb
- test/lib/y2users/password_test.rb
- test/lib/y2users/user_test.rb
In the *users_finish* client, we need to pass two configs to the config writer in order to create the new users. The idea is to read the users from the system, and then to generate a new config from the system one but adding all the user that were stored in *UsersSimple*. Then, the writer would take care of creating the new users by comparing these two configs. Note that the password of root user should be updated if needed.
In order to keep the writer as simple as possible, we need to prepare the target config in a way that the new users can be created and the root password can be updated by the writer. At the same time, the rest of users from system should not be touched at all.
Create a `ConfigMerger` class to merge the users and groups from one config into another config. This will be …
> Add ConfigMerger

- src/lib/users/clients/users_finish.rb
- src/lib/y2users/linux/writer.rb
- test/lib/y2users/linux/writer_test.rb
- test/lib/y2users/user_test.rb
- test/lib/y2users/users_simple/writer_test.rb
- test/users_finish_test.rb
Clients *inst_user_first* and *inst_root_first* were already adapted to use the new `Y2Users` classes, but *users_finish* client is still using the old code to create the users into the system.
The *users_finish* client was adapted to use `Y2Users` classes.
NOTE: *users_finish* is also used by AutoYaST, but the AutoYaST part will be adapted in a separate PR.
* Added unit tests
* Manually tested:
* Autologin is not working (will be fixed in a separate PR)
* Root password form has an issue: https://github.com/yast/yast-users/pull/273
> Adapt users_finish client

- src/lib/users/dialogs/inst_user_first.rb
- src/lib/users/widgets.rb
- src/lib/y2users/inst_users_dialog_helper.rb
- test/lib/y2users/users_simple/writer_test.rb
- test/support/users_helpers.rb
- test/test_helper.rb
- test/widgets_test.rb
Stop using a user attached to the config for performing validations because, as written in the commit message 
> [...] could end up with changes that the user
eventually discarded (e.g., the user changes their mind about using the
same password for the root user)
Instead, it creates a detached _placeholder_ user for it.
> Do not use an attached user for validations

- src/lib/users/widgets.rb
- test/widgets_test.rb
While manually testing https://github.com/yast/yast-users/pull/270, I realize that the root password was not being set as expected because an step missing in https://github.com/yast/yast-users/pull/266: to _write back_ the chosen root password to `Yast::UsersSimple` database.
This PR fix it by updating the UserSimple password in the PasswordWidget#store method, as it was before #266, but ideally it should be relocated in a more appropriate place in future iterations.
* Updated unit tests
* Tested manually too via DUD and proceeding with installation until reach the installed system
> Write root password to Yast::UsersSimple

- src/lib/users/clients/users_finish.rb
- test/users_finish_test.rb
After adapting the [*users_finish* client](https://github.com/yast/yast-users/pull/270) to use the new `Y2Users` classes, the autologin feature is not working anymore.
Autologin config was not written when creating the users. Fixed.
* Added unit tests
* Manually tested
Note: there still is a bug with the root password form, see #273.
> Fix autologin

- src/lib/users/dialogs/inst_user_first.rb
Looks like a `Y2User` namespace was missed while moving code around in #274. This PR _restores_ it.
> Fix missing Y2Users namespace

- src/Makefile.am
- src/lib/y2users/linux/writer.rb
- src/lib/y2users/parsers/shadow.rb
- src/lib/y2users/password.rb
- src/lib/y2users/shadow_date_helper.rb
- src/lib/y2users/users_simple/writer.rb
- test/lib/y2users/linux/writer_test.rb
- test/lib/y2users/password_test.rb
- test/lib/y2users/users_simple/reader_test.rb
- test/lib/y2users/users_simple/writer_test.rb
Main PR for https://trello.com/c/k4Hckc0k/2458-write-other-shadow-attributes
This PR teaches the linux writer to modify all the fields in the shadow file.
It's easier to review commit by commit
> Linux::Writer takes care of shadow attributes

- src/Makefile.am
- src/lib/y2users/config.rb
- src/lib/y2users/config_element.rb
- src/lib/y2users/config_element_collection.rb
- src/lib/y2users/config_merger.rb
- src/lib/y2users/group.rb
- src/lib/y2users/groups_collection.rb
- src/lib/y2users/linux/writer.rb
- src/lib/y2users/password.rb
- src/lib/y2users/user.rb
- src/lib/y2users/users_collection.rb
- test/Makefile.am
- test/lib/y2users/config_element_collection_examples.rb
- test/lib/y2users/config_element_examples.rb
- test/lib/y2users/config_merger_test.rb
- test/lib/y2users/config_test.rb
- test/lib/y2users/group_test.rb
- test/lib/y2users/groups_collection_test.rb
- test/lib/y2users/linux/writer_test.rb
- test/lib/y2users/password_test.rb
- test/lib/y2users/user_test.rb
- test/lib/y2users/users_collection_test.rb
The API for `Y2Users::Config` provides methods like `#users` and `#groups` which return a ruby *Array*. That arrays are usually walked though in order to get some specific elements. For example, to select the *root* user.
These methods should return richer objects like collections which can be easily queried.
Methods like `#users` and `#groups` now return collection classes instead of plain arrays. New classes added: `UsersCollection` and `GroupsCollection`.
Other internal changes:
* Overloaded `#clone` was replaced by `#copy`: `#clone` is kept with its original version (shallow copy) and new `#copy` performs a deep copy.
* `User` and `Group` objects always have an internal id, even for recently created objects that have not been attached yet.
> Add collections

- src/lib/users/clients/users_finish.rb
- src/lib/users/users_database.rb
- src/lib/y2users/config.rb
- src/lib/y2users/config_element_collection.rb
- src/lib/y2users/config_manager.rb
- src/lib/y2users/inst_users_dialog_helper.rb
- src/lib/y2users/linux/local_reader.rb
- src/lib/y2users/linux/reader.rb
- src/lib/y2users/users_simple/reader.rb
- test/lib/y2users/config_manager_test.rb
- test/lib/y2users/config_test.rb
- test/lib/y2users/linux/local_reader_test.rb
- test/lib/y2users/linux/reader_test.rb
- test/lib/y2users/users_simple/reader_test.rb
Currently, readers offer a `#read_to` method which receives a config argument. But having a config parameter is not needed and it could cause misunderstandings.  For example, what happens with the elements that the given config already has? Should the reader draw its elements off before reading? Should the current elements be updated somehow?
Improve the API by removing the config parameter. Now the `#read` method always generates a new config.
> Improve readers API

- src/Makefile.am
- src/lib/y2users/linux/writer.rb
- src/lib/y2users/parsers/shadow.rb
- src/lib/y2users/password.rb
- src/lib/y2users/shadow_date.rb
- src/lib/y2users/user.rb
- src/lib/y2users/users_simple/reader.rb
- src/lib/y2users/users_simple/writer.rb
- test/Makefile.am
- test/lib/y2users/linux/reader_test.rb
- test/lib/y2users/linux/writer_test.rb
- test/lib/y2users/password_test.rb
- test/lib/y2users/shadow_date_test.rb
- test/lib/y2users/user_test.rb
- test/lib/y2users/users_simple/reader_test.rb
- test/lib/y2users/users_simple/writer_test.rb
When the users information is written to *UsersSimple* module and then it is recovered again, it might result in wrong values for some of the password attributes like the "last change date". When this happens, the user could be forced to change his/her password in the first login attempt after the installation.
Use `nil` value to indicate that a password attribute is unknown. When an attribute is `nil`, the linux writer will not pass the attribute to the *chage* commad, keeping the default values set by *chpasswd*. 
Moreover, the users simple reader is now able to keep the `nil` values that comes from the `UsersSimple` module.
* Added unit tests.
* Manually tested.
> Fix aging issues

- src/lib/y2users/linux/writer.rb
- src/lib/y2users/user.rb
- test/lib/y2users/config_merger_test.rb
- test/lib/y2users/linux/writer_test.rb
Bring back be876b7d0cbc28382f6f92c818a645788a1ac043 which added support for `usermod` and was wrongly removed by me when adapting the original PR.
> Modify user attributes (home, gecos, shell and groups)

- src/lib/y2users/help_texts.rb
- src/modules/UsersSimple.pm
`Y2Users::HelpTexts` depends on `Yast::UsersSimple` just for the `Yast::UsersSimple.ValidPasswordHelptext`, which simply returns a localized string.
https://trello.com/c/j0t4rJAZ/2430-1-remove-dependency-of-y2usershelptexts-on-userssimple
As we agreed, for this special case the simpler solution is just to duplicate the localized string in `Y2Users::HelpText`.
Tested manually checking that the translation still working as expected.
> Remove dependency of `Y2Users::HelpTexts` on `UsersSimple`

- package/yast2-users.spec
- src/Makefile.am
- src/lib/y2users/config.rb
- src/lib/y2users/linux/base_reader.rb
- src/lib/y2users/linux/useradd_config_reader.rb
- src/lib/y2users/linux/useradd_config_writer.rb
- src/lib/y2users/linux/writer.rb
- src/lib/y2users/useradd_config.rb
- test/Makefile.am
- test/fixtures/root/etc/default/useradd
- test/lib/users/dialogs/inst_user_first_test.rb
- test/lib/y2users/linux/local_reader_test.rb
- test/lib/y2users/linux/reader_test.rb
- test/lib/y2users/linux/writer_test.rb
- test/lib/y2users/useradd_config_test.rb
This adds management of the useradd configuration, which is important for several reasons:
- The AutoYaST profile can contain a `<user_defaults>` section used to configure useradd
- The YaST UI for managing users also contain a tab for configuring useradd
- The useradd default values must be used in the YaST UI to pre-fill several fields
See also https://github.com/yast/yast-yast2/pull/1166 and https://trello.com/c/vhM38X7J/2463-3-manage-useradd-configuration
> Manage useradd configuration

- src/include/users/routines.rb
[`users/routines`](https://github.com/yast/yast-users/blob/8d0a665f1423a4439f143b957e3c96b114c6f6ae/src/include/users/routines.rb#L109-L176) contains two methods that are no longer needed after https://github.com/yast/yast-users/commit/1b6818ce05463a28471171686f0f6a57c69107e3 and https://github.com/yast/yast-users/commit/4a5ec436df0e191c4e13bf43290c793d03008f60. So, let's drop them.
---
Note: the only [client using `#setup_all_users`](https://github.com/yast/yast-firstboot/blob/b550444a77ffc410aec0e130f8ca0e9fdf445c45/src/lib/y2firstboot/clients/user.rb#L44) lives in yast2-firsboot and will be adapted.
> Remove some dead code

- package/yast2-users.changes
- package/yast2-users.spec
- src/desktop/org.opensuse.yast.Users.desktop
See [bsc#1187270](https://bugzilla.suse.com/show_bug.cgi?id=1187270).
Before:
After:
> bsc#118727: fix control center tooltip

- src/lib/y2users/autoinst/reader.rb
- src/lib/y2users/autoinst_profile/user_defaults_section.rb
- src/lib/y2users/config_merger.rb
- src/lib/y2users/linux/login_config_writer.rb
- src/lib/y2users/useradd_config.rb
- test/lib/users/users_database_test.rb
- test/lib/y2users/autoinst/reader_test.rb
- test/lib/y2users/config_merger_test.rb
This replaces #298.
For details, see https://trello.com/c/QU2gDrTK/2486-3-autoyast-userdefaults-section
This processes the <user_defaults> section of AutoYaST, intentionally ignoring the "groups", "no_groups" and "skel" entries. The first two are not longer relevant for the useradd configuration and are ignored by AutoYaST while creating users during installation (verified for SLE-11-SPX, SLE-12-SPX and SLE-15-SPX with extensive manual tests). The latter cannot be changed via `useradd -D` (so we decided to not persist its value to the final system), must be combined with "usrskel" (which currently is not part of the AutoYaST profile) and is mostly useless during the AutoYaST installation (it's very unlikely that a custom skeleton directory exists at that point).
* `Autoinst::Reader` …
> Third attempt: process user_defaults section from the AutoYaST profile

- src/autoyast-rnc/users.rnc
With the new implementation (Y2Users), the attributes "groups", "no_groups" and "skel" from the `<user_defaults>` section of the AutoYaST profile are now intentionally ignored.
Making a note (with links) about it because we cannot remove them from the schema yet.
> Add note about dropping attributes from the schema

- src/lib/y2users/autoinst/reader.rb
- src/lib/y2users/linux/users_writer.rb
- src/lib/y2users/user.rb
- test/lib/y2users/autoinst/reader_test.rb
- test/lib/y2users/linux/writer_test.rb
Support in `Y2Users` for the AutoYaST attribute `<home_btrfs_subvolume>` (and for creating home as subvolumes in general).
As a bonus, this also makes YaST work in a more backwards-compatible way when the home directory (or subvolume) cannot be created. Instead of aborting the whole creation of the user, YaST now tries to create the user without home directory (which is basically what the old perl-based YaST used to do).
See https://trello.com/c/QHeTE0GY/2505-5-recover-autoyast-home-btrfs-support
- Unit tests included
- Manual tests:
- AutoYaST with a btrfs filesystem and some users using subvolumes. Works as expected.
- AutoYaST with a non-btrfs home and some users using subvolumes. WIP
> Create home as btrfs subvolume

- package/yast2-users.changes
- package/yast2-users.spec
- src/modules/Users.pm
System settings are read when the *users* client starts. But the client is not aware of failures when reading the system settings. The client silently continues, and it applies its own default values for the system settings (e.g., for login.defs values). Everything happens without noticing to the user.
Moreover, the default encryption method is md5 when *login.defs* cannot be read. This is insecure, and sha512 should be the default encryption method.
* https://bugzilla.suse.com/show_bug.cgi?id=1177183
A warning popup is shown when reading system settings fails. And sha512 is the default encryption method now. 
* Requires https://github.com/yast/yast-security/pull/111
* Manually tested
> System settings warning

- package/yast2-users.changes
- package/yast2-users.spec
- src/lib/users/dialogs/inst_user_first.rb
Reported [bsc#1188068](https://bugzilla.suse.com/show_bug.cgi?id=1188068#c12) has revealed that `InstUserFirstDialog` is using a not optimal way to know if the user is going to be created or edited (see comment#12). In fact, changes introduced at https://github.com/yast/yast-firstboot/pull/126 broken it in a way that [`init_pw_for_root`](https://github.com/yast/yast-users/blob/61c0bc6bf2bb595f2d86fe37807868194c44d865/src/lib/users/dialogs/inst_user_first.rb#L195-L209) starts failing.
To use the [`Y2Users::ConfigElement#attached?`](https://github.com/yast/yast-users/blob/61c0bc6bf2bb595f2d86fe37807868194c44d865/src/lib/y2users/config_element.rb#L65) method instead of relying on the password value, which looks prone to false positives.
However, the check has to be performed and stored at …
> Improve knowing when first user is being created or edited

- package/yast2-users.changes
- package/yast2-users.spec
- src/lib/users/ssh_authorized_keyring.rb
- src/lib/users/ssh_authorized_keys_file.rb
- src/modules/Users.pm
- test/lib/users/ssh_authorized_keyring_test.rb
- test/lib/users/ssh_authorized_keys_file_test.rb
As [stated in the documentation](https://documentation.suse.com/sles/15-SP3/html/SLES-all/cha-configuration-installation-options.html#id-1.7.5.2.35.3.5), the `$HOME/.ssh/authorized_keys` file will be overwritten when auto-installing the product via an AutoYaST profile defining a set of authorized_keys
> If the profile defines a set of SSH authorized keys for a user in the authorized_keys section, an existing $HOME/.ssh/authorized_keys file will be overwritten. If not existing, the file will be created with the content specified. Avoid overwriting an existing authorized_keys file by not specifying the respective section in the AutoYaST control file. 
However, as reported at https://bugzilla.suse.com/show_bug.cgi?id=1188361, looks like the file is overwritten even when the profile does not …
> Improve handling of authorized_keys

- package/yast2-users.changes
- package/yast2-users.spec
- src/lib/users/ssh_authorized_keyring.rb
- src/lib/users/ssh_authorized_keys_file.rb
- src/modules/Users.pm
- test/lib/users/ssh_authorized_keyring_test.rb
- test/lib/users/ssh_authorized_keys_file_test.rb
This is a sync of https://github.com/yast/yast-users/pull/320 for `SLE-15-SP3` branch. It fix https://bugzilla.suse.com/show_bug.cgi?id=1188361 by preventing to overwrite the `$HOME/.ssh/authorized_keys` file during auto-installation when none authorized keys have been defined in the profile.
---
This sync PR has been tested manually using a `SLE-15-SP3-Full-x86_64-GM` iso and 
* an AutoYaST profile defining authorized keys for root user
* an AutoYaST profile **not defining** authorized keys
In both cases tests worked as expected.
> [SLE-15-SP3] Improve handling of authorized_keys

- package/yast2-users.changes
- package/yast2-users.spec
- src/lib/users/ssh_authorized_keyring.rb
- src/lib/users/ssh_authorized_keys_file.rb
- src/modules/Users.pm
- test/lib/users/ssh_authorized_keyring_test.rb
- test/lib/users/ssh_authorized_keys_file_test.rb
The same than #320 and #321 but for `master` branch. Tested using an openSUSE Tumbleweed ISO.
>  [master] Improve handling of authorized_keys

- package/yast2-users.changes
- package/yast2-users.spec
- src/lib/users/widgets.rb
- src/lib/y2users/linux/users_writer.rb
- src/lib/y2users/linux/writer.rb
- test/lib/y2users/linux/writer_test.rb
- test/widgets_test.rb
Right now, the `Linux::Writer` class only supports (auto)installation and firstboot use cases. During the installation, users can only be created. And for firstboot and auto-installation, users can be edited too. In firstboot, even the name of the user can be changed when you go back, but the `Linux::Writer` does not modify it in the system.
* https://bugzilla.suse.com/show_bug.cgi?id=1188612
Moreover, the root password is not properly deleted if you go back to the wizard step for setting the root password and remove password (only an authorized key is selected). This affects to both: installation and firstboot.
* https://bugzilla.suse.com/show_bug.cgi?id=1189402
Extend `Linux::Writer` in order to support the use cases mentioning above.
See also …
> Extend Linux writer

- doc/attributes.md
Add document to describe the correspondence between `Yast::Users` data structure and `Y2Users` attributes.
> Document supported attributes

- doc/attributes.md
- src/lib/y2users/autoinst/reader.rb
- src/lib/y2users/collection.rb
- src/lib/y2users/commit_config.rb
- src/lib/y2users/commit_config_collection.rb
- src/lib/y2users/config_element_collection.rb
- src/lib/y2users/home.rb
- src/lib/y2users/linux/base_reader.rb
- src/lib/y2users/linux/users_writer.rb
- src/lib/y2users/linux/writer.rb
- src/lib/y2users/parsers/passwd.rb
- src/lib/y2users/user.rb
- src/lib/y2users/users_module/commit_config_reader.rb
- src/lib/y2users/users_module/reader.rb
- test/lib/y2users/autoinst/reader_test.rb
- test/lib/y2users/commit_config_collection_test.rb
- test/lib/y2users/commit_config_test.rb
- test/lib/y2users/home_test.rb
- test/lib/y2users/linux/base_reader_test.rb
- test/lib/y2users/linux/local_reader_test.rb
- test/lib/y2users/linux/reader_test.rb
- test/lib/y2users/linux/writer_authorized_keys_test.rb
- test/lib/y2users/linux/writer_errors_test.rb
- test/lib/y2users/linux/writer_root_aliases_test.rb
- test/lib/y2users/linux/writer_settings_test.rb
- test/lib/y2users/linux/writer_test.rb
- test/lib/y2users/user_test.rb
- test/lib/y2users/users_module/commit_config_reader_test.rb
- test/lib/y2users/users_module/reader_test.rb
The new `Y2Users` classes support creating and editing users. Right now, such classes are only used for (auto)installation and firstboot. That new classes use the shadow tools to probe and commit users. We plan start using them for the YaST users client instead of the `Yast::Users` module. But the users client allows to manipulate more user attributes than the currently supported by `Y2Users`. So, `Y2Users` needs to be extended in order to support all the use cases provided by YaST users client.
Internal links:
* https://trello.com/c/44pVMU58/2656-5-modifying-users-with-y2users
* https://trello.com/c/qfPotJsP/2649-8-missing-attributes-for-interactive-execution
* https://jira.suse.com/browse/SLE-20592
`Y2Users` classes were extended to support all the required attributes for creating and …
> Edit users

- src/include/users/helps.rb
- src/include/users/widgets.rb
- src/modules/Users.pm
- src/modules/Y2UsersLinux.rb
The YaST users client has a tab for editing the useradd settings (i.e., */etc/default/useradd*). The current useradd config is read by the *Users* module, which directly parses */etc/default/useradd*. But such a file could not exist in the system, so *Users* module would propose its own default values instead of relying on the default values proposed by the shadow tools (*useradd -D* command). Moreover, some of the values offered by the "Defaults for New Users" tab are not supported by the shadow tools anymore, for example *skel* and *groups*.    
* https://trello.com/c/hWPBYvVY/2651-3-use-y2usersuseraddconfig-from-to-yastusers
* Part of https://jira.suse.com/browse/SLE-20563
Unsupported attributes are removed from the UI (*skel* and *groups*), and the …
> Read useradd config

- src/modules/Users.pm
This is part of the big modification we are doing in the separate `y2users` branch in order to ensure the interactive module of YaST2 uses the `shadow` tools under the hood.
We were not sure whether the UI option "Expert Options -> Password Encryption" would still work after the changes. It does work correctly and this pull request simply adds a comment explaining why.
In short, changing the option takes effect immediately and will affect all the users created after altering the value. Users created in the same YaST execution but before changing the value retain the previous encryption method. The value is finally written to the `login.defs` configuration just to make it persistent, but not to affect the current execution.
> Document relationship of WriteSecurity and Y2Users writer

- src/lib/y2users/linux/set_auth_keys_action.rb
- src/lib/y2users/linux/users_writer.rb
- test/lib/y2users/linux/set_auth_keys_action_test.rb
- test/lib/y2users/linux/users_writer_test.rb
Manual testing revealed that after changes introduced in #349 SSH Public Keys are not being added or modified anymore. That issue happens because `Yast::Users::SSHAuthorizedKeyring` needs both, news and previous SSH public keys to know if it must proceed when its public  `#write_keys` method is called (see #320). However, the new `Y2Users::Linux::SetAuthKeysAction` is providing only the new/updated keys, which is only half of the information needed.
Adapt the action to set both, previous and new SSH public keys before calling `#write_keys`.
* Adapted unit tests
* Tested manually in a running system
> Make SetAuthKeys action aware of previous keys 

- src/lib/y2users/linux/users_writer.rb
- test/lib/y2users/linux/users_writer_test.rb
When installing via an AutoYaST profile setting [`<authorized_keys>`](https://doc.opensuse.org/projects/autoyast/#id-1.9.5.2.34.3.9.14) for users the system is installed without provided SSH public keys, as reported in http://bugzilla.suse.com/show_bug.cgi?id=1192178.
The problem is in the [check for user home existence](https://github.com/yast/yast-users/blob/f6d4a583ee13c16201145bf68e2f2028e55d9e76/src/lib/y2users/linux/users_writer.rb#L328-L332), which is looking at `/home/<username>` instead `/mnt/home<username>` during installation.
~~Use `Yast::Execute.on_target!` and `stat` from [GNU core utils](https://github.com/coreutils/coreutils) command instead of [File.exist?](https://ruby-doc.org/core-3.0.2/File.html#method-c-exist-3F) Ruby method.~~
Use …
> Fix check for user home existence

- src/lib/y2users/linux/base_reader.rb
- src/lib/y2users/linux/reader.rb
- test/lib/y2users/linux/base_reader_test.rb
- test/lib/y2users/linux/local_reader_test.rb
- test/lib/y2users/linux/reader_test.rb
Adapt Linux readers to read home permissions and root aliases too.
* https://trello.com/c/UIMO6uJg/2655-1-missing-atributes-on-linuxreader
> Read home permissions and root aliases

- src/autoyast-rnc/users.rnc
- src/lib/y2users/autoinst/reader.rb
- src/modules/Users.pm
- test/lib/y2users/autoinst/reader_test.rb
The [not so widespread](https://unix.stackexchange.com/questions/93123/typical-use-case-for-a-group-password) _passworded_ group feature is considered
> _an inherent security problem since more than one person is permitted to know the password._ — https://www.man7.org/linux/man-pages/man1/gpasswd.1.html
Thus, the support for it in yast2-users will be dropped in the [new code base relying on shadow tools](https://github.com/yast/yast-users/pull/349).
Stop supporting it in the new yast2-users code base, for which the below actions have been taken
* Do not export either, `<group_password>` or `<encrypted>` tags to the AutoYaST profile.
* Do not look for those values while importing groups.
* Be compatible with old generated profiles holding group passwords by creating the group **without** …
> Do not support group passwords

- src/include/users/dialogs.rb
- src/lib/users/dialogs/inst_user_first.rb
- src/lib/y2users/config.rb
- src/lib/y2users/linux/create_user_action.rb
- src/lib/y2users/user.rb
- test/lib/users/dialogs/inst_user_first_test.rb
- test/lib/y2users/linux/create_user_action_test.rb
- test/lib/y2users/linux/set_auth_keys_action_test.rb
- test/lib/y2users/linux/users_writer_test.rb
- test/lib/y2users/user_test.rb
In the *YaST users* client, leaving the "Home Directory" field as empty leads to a weird behavior. The old code really left the field empty in */etc/passwd* and skipped the creation of the directory. But that behavior was probably fully unintended since the empty "Home Directory" field was automatically re-filled with the default data on every tab switch. Note that leaving the */etc/passwd* field empty doesn't seem to be fully correct - the possibility is not mentioned in the man page for */etc/passwd* and `su` complains saying the entry is incomplete.
Currently, `Y2Users::Linux::Writer` does not create the home directory for a local user if the home path is unknown. But `useradd` always adds the default home path to */etc/passwd*. Because of that, the current behaviour of *YaST users* …
> Always create home

- src/modules/Users.pm
The [Users module](https://github.com/yast/yast-users/blob/39c07e262368c52110024a513c81c9504f9d3fae/src/modules/Users.pm) was not reseting its internal data structure for removed elements after each write action.
With previous code writing the _/etc/passwd_ and _/etc/groups_ files directly, this was not a problem. It simply didn't write the elements marked as deleted to those files. Now that [new code](#349) is running a `userdel` and `groupdel` commands to remove them, an error for the first previously deleted element is prompted after running a "Write Changes Now" action.
It happens because those removed lists are used by the new readers (see [here]( https://github.com/yast/yast-users/blob/39c07e262368c52110024a513c81c9504f9d3fae/src/lib/y2users/users_module/reader.rb#L118-L124) and …
> Flush deleted users and groups after each write

- src/lib/y2users/users_module/reader.rb
- test/lib/y2users/users_module/reader_test.rb
There are issues when a user is added in the "YaST client" and the option "Write Changes Now" is used to save the changes into the system:
* The next time that `Linux::Writer` is called (i.e., by clicking "Ok" or "Write Changes Now"), it tries to create the new users and groups again.
* When editing a group to add a user to its list, the writer complains if the user does not exist in the system yet (i.e., the user is new).
The detection of new users and groups by `UsersModule::Reader` was wrong. It was based on the *what* attribute, which usually contains "add_user" or "add_group" when the user/group is new. But that is not always true. In some cases, for example when a user is added to a group, the "what" attribute contains other values like "group_change". Because of that, the …
> Fix UsersModule::Reader

- package/yast2-users.changes
- package/yast2-users.spec
- src/lib/y2users/autoinst/reader.rb
- test/lib/y2users/autoinst/reader_test.rb
Although YaST [does not support group passwords anymore](https://github.com/yast/yast-users/pull/353) and ignores them when importing the profile, the user receives a warning about it ONLY when the found `<group_password>` does not mean "no password". I.e, when the value is neither, empty nor `x`.
However, other values like `!` and `*` are used to express the absence of the group password too BUT we are warning the user about ignoring such a _no password_. See https://openqa.suse.de/tests/7757865#step/installation/48 (if it has not expired yet)
<table>
<thead>
<tr>
<th>The AutoYaST profile excerpt</th>
<th>The wrong/not needed warning</th>
</tr>
</thead>
<tbody>
<tr>
<td>
```xml
<group>
<encrypted config:type="boolean">true</encrypted>
<gid>483</gid>
<group_password>x</group_password> …
```
> AutoYaST: Improve ignored group passwords

- package/yast2-users.changes
- package/yast2-users.spec
- src/lib/users/dialogs/inst_user_first.rb
- src/lib/y2users/group.rb
- test/lib/users/dialogs/inst_user_first_test.rb
Now, YaST relys on the shadow tools for creating users and groups. The `useradd` command fails if the given *gid* does not exist. This situation could happen when importing users from a previous installation. It worked with the old code because *gid* was sanitized before writing the *passwd* file, falling back to a default *gid*.
* https://bugzilla.suse.com/show_bug.cgi?id=1197040
* https://trello.com/c/O0yWuGtg/2787-2-importing-a-user-with-unknown-gid
Remove *gid* from the imported users when such a group is not present in the configuration. Note that `useradd` will assign the default group according to the */etc/default/useradd* config.
NOTE: this PR will be merged into *pre-SLE-15-SP4* branch. That branch will be merged into master after branching SLE-15-SP4.
- Added a new unit test
- …
> Fix import users

- package/yast2-users.changes
- package/yast2-users.spec
- src/lib/y2users/linux/users_writer.rb
- test/lib/y2users/linux/users_writer_test.rb
When in autoyast profile home path is not specied, then ssh keys are not written.
- https://bugzilla.suse.com/show_bug.cgi?id=1201185
Read system users again before writting ssh keys to know its home paths.
- *Unit tests adapted*
- *Tested manually*
> Fix ssh keys nohome

- package/yast2-users.changes
- package/yast2-users.spec
- src/lib/y2users/home.rb
- src/lib/y2users/linux/create_user_action.rb
- test/lib/y2users/home_test.rb
- test/lib/y2users/linux/create_user_action_test.rb
The home directory is not created for the system users (uid <= SYS_MAX_UID) even though a home dir is indicated in the AutoYaST profile.
The bug was introduced in the *yast-users* code refactoring for relying on the shadow tools (SLE-15-SP4).
* https://trello.com/c/z0nqzV8t/3076-sles15-sp4-p2-1202974-l3-setting-of-users-home-directory-ignored-by-autoyast-in-sles15-sp4
* https://bugzilla.suse.com/show_bug.cgi?id=1202974
Create home directory for system users if a home dir is indicated.
- Added new unit tests
- Tested manually
> Create home for system users

- package/yast2-users.changes
- package/yast2-users.spec
- src/modules/Users.pm
- test/lib/users/local_password_test.rb
https://bugzilla.suse.com/show_bug.cgi?id=1205783
https://trello.com/c/IEHa2Ffx/
When trying to create a new user group on a newly installed Tumbleweed, you always get an error popup about the permitted characters for the group name:
```
The name of the group may only contain letters, digits, 
"-", ".", and "_" and must start with a letter.
Please try again.
```
Even though that group name fullfilled those criteria.
The `/usr/etc/login.defs` or `/etc/login.defs` file on Tumbleweed now no longer contains a CHARACTER_CLASS field. The code, however, just overwrote the internal variable holding the contents of that field, and if nothing could be read, it would remain empty; and comparing the group name that the user entered against that always failed.
Handle that case gracefully: Fall back to …
> Use Fallback for CHARACTER_CLASS

- package/yast2-users.changes
- package/yast2-users.spec
- src/modules/Users.pm
YaST offers the option "Create as Btrfs Subvolume" when creating a new user. Of course, this is optional and only possible when the home directory of the new user is part of a Btrfs file system.
As reported at [bsc#1209377](https://bugzilla.suse.com/show_bug.cgi?id=1209377), this sequence of actions caused that flag to be set, even if didn't make sense for the affected users.
1) Open YaST Users
2) In the tab "Users" click "Add" and enter the information for a new user
3) When back to the list of users, click in that new user and choose "Edit"
4) Visit the tab "details" without making any change
5) Click "ok" -> "ok" to save the changes and quit YaST.
In the best case, the home was created as a Btrfs subvolume when not really wanted. In the worst case (system not using Btrfs), the creation …
> [SP4] Stop mangling btrfs_subvolume as boolean at Users.EditUser

- package/yast2-users.changes
- package/yast2-users.spec
- src/lib/y2users/home.rb
- src/lib/y2users/linux/create_user_action.rb
- src/modules/Users.pm
- test/lib/y2users/home_test.rb
- test/lib/y2users/linux/create_user_action_test.rb
Merge of #376 (which fixes [bsc#1209377](https://bugzilla.suse.com/show_bug.cgi?id=1209377)), into the SLE-15-SP5 branch.
While doing so, I found that #370 was fixed only in SLE-15-SP4 and never merged to more modern branches. Since @joseivanlopez cannot remember a good reason for that, we guess it was simply overlooked. So I'm taking the opportunity to merge also that pull request (which fixed [bsc#1202974](https://bugzilla.suse.com/show_bug.cgi?id=1202974)).
> [SP5] Stop mangling btrfs_subvolume as boolean at Users.EditUser

- package/yast2-users.changes
- package/yast2-users.spec
- src/lib/users/clients/auto.rb
- test/lib/users/clients/auto_test.rb
* [bsc#1211753](https://bugzilla.suse.com/show_bug.cgi?id=1211753)
Users are not written when using AutoYaST on an already installed system, neither using `ayast_setup` nor the AutoYaST UI. In those scenarios, the process of detecting which users/groups changed is tricky:
* The approach followed by [Y2Users::UsersModule::Reader](https://github.com/yast/yast-users/blob/414b6c7373068c367c0a01be20a1399fbd0ef470/src/lib/y2users/users_module/reader.rb#L103), checking the content of `org_user`, does not work because it is defined only if the user was modified using the AutoYaST UI.
* Directly comparing the users/groups from `system_config` and `target_config` does not work because passwords are missing from the `target_config` users.
```
{
:class=>Y2Users::User, :name=>"systemd-timesync", …
```
> Write users when running AutoYaST on an installed system

- package/yast2-users.changes
- package/yast2-users.spec
SLE 15 SP6 branch is based on SLE15 SP5 maintenance branch. So fixes done in master can be sometimes useful also for SP6.
All fixes are already in SP5, so just update version to the latest in 4.6.X
> Backport SP6

- package/yast2-users.changes
- package/yast2-users.spec
- src/modules/Users.pm
This is for **SLE-15-SP6**. A merge to Factory / TW will follow.
https://bugzilla.suse.com/show_bug.cgi?id=1228149
https://trello.com/c/PLxx2iDV
PAM in connection with some desktops like GNOME need an _umask_ specification to be set in the GECOS field (the comment / full user name field) in `/etc/passwd`.
But the YaST users module complains that only 3 fields separated by commas are permitted:
This is triggered when trying to leave that tab.
There is an additional check in the ancient `Users.pm` Perl module that dates back to 2004. Why this check exists is unclear; there doesn't seem to be a reference why this limitation was introduced.
Removed that check.
Manual test in a TW VM. After removing this check, it doesn't complain anymore, and `/etc/password` now contains the expected entry: …
> Relax Check in GECOS Field: Allow any Data except Colons [SLE-15-SP6]

- package/yast2-users.changes
- package/yast2-users.spec
- src/modules/Users.pm
This is for the merge of  #395 to **master**.
https://bugzilla.suse.com/show_bug.cgi?id=1228149
https://trello.com/c/PLxx2iDV
PAM in connection with some desktops like GNOME need an _umask_ specification to be set in the GECOS field (the comment / full user name field) in `/etc/passwd`.
But the YaST users module complains that only 3 fields separated by commas are permitted:
This is triggered when trying to leave that tab.
There is an additional check in the ancient `Users.pm` Perl module that dates back to 2004. Why this check exists is unclear; there doesn't seem to be a reference why this limitation was introduced.
Removed that check.
Manual test in a TW VM. After removing this check, it doesn't complain anymore, and `/etc/password` now contains the expected entry:
```console
% grep …
```
> Relax Check in GECOS Field: Allow any Data except Colons [master]

- package/yast2-users.changes
- package/yast2-users.spec
- test/fixtures/root-missing-files/etc/login.defs
- test/fixtures/root/etc/login.defs
https://bugzilla.suse.com/show_bug.cgi?id=1231006
https://github.com/yast/yast-security/pull/160
This removes obsolete parameters from `/etc/login.defs`:
- USERADD_CMD
- USERDEL_PRECMD
- USERDEL_POSTCMD
- USERADD_CMD
More details at the [main PR](https://github.com/yast/yast-security/pull/160).
> Drop Obsolete login.defs Scripts USERADD_CMD, USERDEL_PRECMD, USERDEL_POSTCMD, USERADD_CMD

- package/yast2-users.changes
- package/yast2-users.spec
- test/users_test.rb
- Temporarly disable Users#Export tests
- Bump version and update changes file
See [bsc#1245519](https://bugzilla.suse.com/show_bug.cgi?id=1245519) for further details as it is not used in SLFO anyways.
> Temporarily disable Users#Export tests"

- package/yast2-users.changes
- package/yast2-users.spec
- test/lib/users/clients/auto_test.rb
Temporarly disable auto client tests.
Follow-up of #401.
> Disable auto client unit tests
